// Code generated by MockGen. DO NOT EDIT.
// Source: claim/kava_client.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	codec "github.com/cosmos/cosmos-sdk/codec"
	types "github.com/cosmos/cosmos-sdk/types"
	types0 "github.com/cosmos/cosmos-sdk/x/auth/types"
	gomock "github.com/golang/mock/gomock"
	types1 "github.com/kava-labs/kava/x/bep3/types"
	types2 "github.com/tendermint/tendermint/rpc/core/types"
	types3 "github.com/tendermint/tendermint/types"
)

// MockKavaChainClient is a mock of KavaChainClient interface.
type MockKavaChainClient struct {
	ctrl     *gomock.Controller
	recorder *MockKavaChainClientMockRecorder
}

// MockKavaChainClientMockRecorder is the mock recorder for MockKavaChainClient.
type MockKavaChainClientMockRecorder struct {
	mock *MockKavaChainClient
}

// NewMockKavaChainClient creates a new mock instance.
func NewMockKavaChainClient(ctrl *gomock.Controller) *MockKavaChainClient {
	mock := &MockKavaChainClient{ctrl: ctrl}
	mock.recorder = &MockKavaChainClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKavaChainClient) EXPECT() *MockKavaChainClientMockRecorder {
	return m.recorder
}

// BroadcastTx mocks base method.
func (m *MockKavaChainClient) BroadcastTx(tx types3.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastTx", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// BroadcastTx indicates an expected call of BroadcastTx.
func (mr *MockKavaChainClientMockRecorder) BroadcastTx(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastTx", reflect.TypeOf((*MockKavaChainClient)(nil).BroadcastTx), tx)
}

// GetAccount mocks base method.
func (m *MockKavaChainClient) GetAccount(address types.AccAddress) (types0.AccountI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", address)
	ret0, _ := ret[0].(types0.AccountI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockKavaChainClientMockRecorder) GetAccount(address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockKavaChainClient)(nil).GetAccount), address)
}

// GetChainID mocks base method.
func (m *MockKavaChainClient) GetChainID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChainID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChainID indicates an expected call of GetChainID.
func (mr *MockKavaChainClientMockRecorder) GetChainID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChainID", reflect.TypeOf((*MockKavaChainClient)(nil).GetChainID))
}

// GetCodec mocks base method.
func (m *MockKavaChainClient) GetCodec() *codec.Codec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCodec")
	ret0, _ := ret[0].(*codec.Codec)
	return ret0
}

// GetCodec indicates an expected call of GetCodec.
func (mr *MockKavaChainClientMockRecorder) GetCodec() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCodec", reflect.TypeOf((*MockKavaChainClient)(nil).GetCodec))
}

// GetOpenOutgoingSwaps mocks base method.
func (m *MockKavaChainClient) GetOpenOutgoingSwaps() (types1.AtomicSwaps, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenOutgoingSwaps")
	ret0, _ := ret[0].(types1.AtomicSwaps)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenOutgoingSwaps indicates an expected call of GetOpenOutgoingSwaps.
func (mr *MockKavaChainClientMockRecorder) GetOpenOutgoingSwaps() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenOutgoingSwaps", reflect.TypeOf((*MockKavaChainClient)(nil).GetOpenOutgoingSwaps))
}

// GetRandomNumberFromSwap mocks base method.
func (m *MockKavaChainClient) GetRandomNumberFromSwap(id []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomNumberFromSwap", id)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomNumberFromSwap indicates an expected call of GetRandomNumberFromSwap.
func (mr *MockKavaChainClientMockRecorder) GetRandomNumberFromSwap(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomNumberFromSwap", reflect.TypeOf((*MockKavaChainClient)(nil).GetRandomNumberFromSwap), id)
}

// GetTxConfirmation mocks base method.
func (m *MockKavaChainClient) GetTxConfirmation(txHash []byte) (*types2.ResultTx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTxConfirmation", txHash)
	ret0, _ := ret[0].(*types2.ResultTx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTxConfirmation indicates an expected call of GetTxConfirmation.
func (mr *MockKavaChainClientMockRecorder) GetTxConfirmation(txHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTxConfirmation", reflect.TypeOf((*MockKavaChainClient)(nil).GetTxConfirmation), txHash)
}
